apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kgazer.fullname" . }}
  labels:
    {{- include "kgazer.labels" . | nindent 4 }}
data:
  config.yml: |
    kafka:
      clusters:
        {{- range .Values.kafka.clusters }}
        - name: {{ .name | quote }}
          bootstrapServers: {{ .bootstrapServers | quote }}
          {{- if .properties }}
          properties:
            {{- range $k, $v := .properties }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- if .schemaRegistry }}
          schemaRegistry: {{ .schemaRegistry | quote }}
          {{- end }}
        {{- end }}
    kgazer:
      server:
        port: {{ .Values.kgazer.server.port }}
      db:
        host: {{ include "kgazer.databaseHost" . }}
        port: {{ include "kgazer.databasePort" . }}
        name: {{ include "kgazer.databaseName" . }}
        user: {{ include "kgazer.databaseUser" . }}
        password: KGAZER_DB_PASSWORD_PLACEHOLDER
        sslmode: {{ include "kgazer.databaseSSLMode" . }}
      compactedOnly: {{ .Values.kgazer.compactedOnly }}
