{{- if not (and .Values.externalDatabase.enabled .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kgazer.fullname" . }}
  labels:
    {{- include "kgazer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.externalDatabase.enabled }}
  db-password: {{ .Values.externalDatabase.password | quote }}
  {{- else }}
  db-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- range $i, $cluster := .Values.kafka.clusters }}
  {{- if and $cluster.sasl $cluster.sasl.username }}
  kafka-sasl-username-{{ $i }}: {{ $cluster.sasl.username | quote }}
  {{- end }}
  {{- if and $cluster.sasl $cluster.sasl.password }}
  kafka-sasl-password-{{ $i }}: {{ $cluster.sasl.password | quote }}
  {{- end }}
  {{- if and $cluster.schemaRegistryAuth $cluster.schemaRegistryAuth.username }}
  sr-username-{{ $i }}: {{ $cluster.schemaRegistryAuth.username | quote }}
  {{- end }}
  {{- if and $cluster.schemaRegistryAuth $cluster.schemaRegistryAuth.password }}
  sr-password-{{ $i }}: {{ $cluster.schemaRegistryAuth.password | quote }}
  {{- end }}
  {{- end }}
{{- end }}
