apiVersion: v2
name: kgazer
description: Kafka Compacted Topic Explorer
type: application
version: 0.1.0
appVersion: "0.3.0"
home: https://github.com/alfonsojimenez/kgazer
sources:
  - https://github.com/alfonsojimenez/kgazer
maintainers:
  - name: Alfonso Jimenez
    url: https://github.com/alfonsojimenez
keywords:
  - kafka
  - compacted-topics
  - explorer
  - consumer-groups

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
